# Acrylamid install for www.asgaard.org
language: python

branches:
  only:
    - master
    
notifications:
  email:
    recipients:
      - travis-ci@cdl.asgaard.org
    on_success: always
    on_failure: always

install:

    - travis_retry git clone https://github.com/s3tools/s3cmd.git
    - travis_retry cd s3cmd
    - travis_retry sudo python setup.py install
    - travis_retry easy_install -U acrylamid

script:
    - acrylamid compile
    - acrylamid deploy
    
