# Acrylamid install for www.asgaard.org
language: python

notifications:
  email:
    - $EMAIL_ADDR

install:

    - travis_retry git clone https://github.com/s3tools/s3cmd.git
    - travis_retry cd s3cmd
    - travis_retry sudo python setup.py install
    - travis_retry easy_install -U acrylamid=0.7.8

script:
    - acrylamid compile
    - acrylamid deploy
    
