# Acrylamid install for www.asgaard.org
language: python

install:

    - sudo apt-get install s3cmd
    - travis_retry easy_install -U acrylamid

script:
    - acrylamid compile
    - acrylamid deploy
    
notifications:
  email:
    - $EMAIL_ADDR
