language: python
branches:
  only:
  - master
sudo: false
notifications:
  email:
    recipients:
    - travis-ci@cdl.asgaard.org
    on_success: always
    on_failure: always
  slack:
    secure: aLCFi+guVC9eYeH/23i+2ansUlYIHctYaiLZPHWM3gOc0mrRGJC/LaFJXkMIlznUFZ9hmTsbMl0ldhynGliYW4+ngrs6vCQQpURvcCQXlBnloEYa74orAKHugz9c0mAcPDpo7Q88LmIg1rlXFcXyyhvS/BUKCooFJp/H0cx38yQ=
install:
- travis_retry easy_install -U acrylamid
addons:
  apt:
    sources:
    - s3tools
    packages:
    - s3cmd
script:
- acrylamid compile
- acrylamid deploy
