# Acrylamid install for www.asgaard.org
language: python

notifications:
  email:
    - $EMAIL_ADDR

install:

    - travis_retry wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -
    - travis_retry sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install s3cmd
    - travis_retry easy_install -U acrylamid

script:
    - acrylamid compile
    - acrylamid deploy
    
